DATA:
  VIDEO_FILE: "/home/wgf/Downloads/leakwater.mp4"

METHOD:
  IMAGE_SHAPE: [3,608,608] # C-H-W
  DETECTION_POS: [100,100,900,800] # x_min, y_min, x_max, y_max.
  FLOW_METHOD: "LK"
  TERM_CRITERIA_MAX_COUNT: 10
  TERM_CRITERIA_EPSILON: 0.03
  MAX_CORNERS: 100
  QUALITY_LEVEL: 0.3
  MIN_DIST: 7
  BLOCK_SIZE: 7
  USE_HARRIS_DETECTOR: False
  SIFT_K: 0.04
  PLK_MAX_LEVEL: 2
  THRESHOLD_LEN: 2
  THRESHOLD: 0.3
  RESET_COUNT: 20
  ENABLE_MOVING_AVERAGE: True
  MOVING_LEN: 10
  USE_GPU: True


POST_PROCESS:
  POST_TEXT: "Water Leak Warning"
  DRAW_LINE_WIDTH: 2
  DRAW_PLOT_RADIUS: 5
  DRAW_LINE_COLOR: [255,0,0]
  DRAW_LINE_COLOR_THRES: [0,0,255]
  TEXT_LINE_WIDTH: 2.6
  TEXT_FONT_SIZE: 2.0
  TEXT_LINE_COLOR: [255,0,0]
  TEXT_OFFSET_X: 800
  TEXT_OFFSET_Y: 50