DATA:
  VIDEO_FILE: "/home/wgf/Downloads/leakwater.mp4"

METHOD:
  IMAGE_SHAPE: [3,608,608] # C-H-W
  DETECTION_POS: [100,150,1500,1000] # x_min, y_min, x_max, y_max.
  FLOW_METHOD: 1 # denotes the farneBack method. 0 for LK.
  LK_TERM_CRITERIA_MAX_COUNT: 10
  LK_TERM_CRITERIA_EPSILON: 0.03
  LK_MAX_CORNERS: 100
  LK_QUALITY_LEVEL: 0.3
  LK_MIN_DIST: 7
  LK_BLOCK_SIZE: 7
  LK_USE_HARRIS_DETECTOR: False
  LK_SIFT_K: 0.04
  LK_PLK_MAX_LEVEL: 2
  FB_PYR_SACLE: 0.5
  FB_LEVELS: 3
  FB_WINSIZE: 15
  FB_ITERATIONS: 3
  FB_POLY_N: 5
  FB_POLYSIGMA: 1.2
  FB_FLAGS: 0
  THRESHOLD_LEN: 2
  THRESHOLD: 0.9
  THRESHOLD_UPPER: 160.0
  RESET_COUNT: 100
  ENABLE_MOVING_AVERAGE: True
  MOVING_LEN: 10
  USE_GPU: True


POST_PROCESS:
  POST_TEXT: "Water Leak Warning"
  DRAW_LINE_WIDTH: 2
  DRAW_PLOT_RADIUS: 5
  DRAW_LINE_COLOR: [255,0,0]
  DRAW_LINE_COLOR_THRES: [0,0,255]
  TEXT_LINE_WIDTH: 2.6
  TEXT_FONT_SIZE: 2.0
  TEXT_LINE_COLOR: [255,0,0]
  TEXT_OFFSET_X: 800
  TEXT_OFFSET_Y: 50